name: Repo Stats

on:
  schedule:
    - cron: '00 11 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: narukoshin/repo-readme-stats@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_OWNER: THERXWOLD
          REPO_NAME: ELU
          COMMIT_BY_ME: True
